name: Build DevBuild
on:
    push:
        branches:
            - main
        paths:
            - .github/workflows/build.yml
            - src/**
            - browser/**
            - scripts/build/**
            - package.json
            - pnpm-lock.yaml
env:
    FORCE_COLOR: true

jobs:
    Build:
        runs-on: ubuntu-latest
        outputs:
            files: ${{ steps.list_files.outputs.files }}

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3 # Install pnpm using packageManager key in package.json

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build web
              run: pnpm buildWebStandalone

            - name: Build
              run: pnpm build --standalone

            - name: Generate plugin list
              run: pnpm generatePluginJson dist/plugins.json dist/plugin-readmes.json

            - name: Clean up obsolete files
              run: |
                  rm -rf dist/*-unpacked dist/vendor Vencord.user.css vencordDesktopRenderer.css vencordDesktopRenderer.css.map

            - name: List files for artifacts
              id: list_files
              run: |
                echo "files=$(ls dist/* | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: 1.All-In-One
                  path: dist/

            - name: Get some values needed for the release
              id: release_values
              run: |
                  echo "release_tag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

            - name: Upload DevBuild as release
              if: github.repository == 'HvTcCore/VencordFrk'
              run: |
                  gh release upload devbuild --clobber dist/*
                  gh release edit devbuild --title "DevBuild $RELEASE_TAG"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  RELEASE_TAG: ${{ env.release_tag }}

    Upload-Artifacts:
        needs: Build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                file: ${{ fromJson(needs.Build.outputs.files) }}
        steps:
            - uses: actions/download-artifact@v4
              with:
                  name: 1.All-In-One
                  path: dist

            - name: Get filename
              id: filename
              run: echo "name=$(basename ${{ matrix.file }})" >> $GITHUB_OUTPUT

            - name: Upload Individual Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ steps.filename.outputs.name }}
                  path: ${{ matrix.file }}